version: "3.4"

x-common: &common
  build: .
  volumes:
    - ./scenarios:/scenarios
  environment: &common-env
    TARGET_URL: https://grandcolline.com
    SCENARIO_FILE: /scenarios/order_flow.py

services:
  master:
    <<: *common
    ports:
      - 8080:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master

  slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      MASTER_HOST: master
